clone:
  git:
    image: plugins/git
    recursive: true
    submodule_update_remote: true

pipeline:
  build:
    image: maven:3.5
    commands:
    - cd kafka-elastic-sink-connector && mvn clean package && cd ..
    - cd debezium && mvn clean package -DskipTests=true && cd ..
    when:
      event:
      - push
      - tag
  package:
    image: plugins/docker
    repo: sansare/kafka-connect
    tags:
    - ${DRONE_BRANCH//\//_}
    - ${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    secrets:
    - docker_username
    - docker_password
    when:
      event:
      - push
  package:
    image: plugins/docker
    repo: sansare/kafka-connect
    tags:
    - '${DRONE_TAG}'
    - latest
    secrets:
    - docker_username
    - docker_password
    when:
      event:
      - tag
  deploy2nightly:
    image: jackthestripper/drone_setimage
    object: kafka-connect
    kind: deployment
    namespace: default
    img_names: sansare/kafka-connect
    img_cnts: kafka-connect
    img_tags: '${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}'
    secrets:
    - source: k8s_nightly_ca
      target: k8s_ca
    - source: k8s_nightly_user
      target: k8s_user
    - source: k8s_nightly_token
      target: k8s_token
    - source: k8s_nightly_addr
      target: k8s_addr
    when:
      branch: master
      event: push
  deploy2stage:
    image: jackthestripper/drone_setimage
    object: kafka-connect
    kind: deployment
    namespace: default
    img_names: sansare/kafka-connect
    img_cnts: kafka-connect
    img_tags: '${DRONE_TAG}'
    secrets:
    - source: k8s_stage_ca
      target: k8s_ca
    - source: k8s_stage_user
      target: k8s_user
    - source: k8s_stage_token
      target: k8s_token
    - source: k8s_stage_addr
      target: k8s_addr
    when:
      event: tag

###
# Deploy to stable / production
###

  deploy2stable:
    image: jackthestripper/drone_setimage
    object: kafka-connect
    kind: deployment
    namespace: default
    img_names: sansare/kafka-connect
    img_cnts: kafka-connect
    img_tags: '${DRONE_BRANCH//\//_}${DRONE_PARENT_BUILD_NUMBER}'
    secrets:
    - source: k8s_stable_ca
      target: k8s_ca
    - source: k8s_stable_user
      target: k8s_user
    - source: k8s_stable_token
      target: k8s_token
    - source: k8s_stable_addr
      target: k8s_addr
    when:
      event: deployment
      environment: stable
  deploy2production:
    image: jackthestripper/drone_setimage
    namespace: default
    kind: deployment
    object: kafka-connect
    img_names: sansare/kafka-connect
    img_tags: '${DRONE_TAG}'
    img_cnts: kafka-connect
    secrets:
    - source: k8s_prod_ca
      target: k8s_ca
    - source: k8s_prod_user
      target: k8s_user
    - source: k8s_prod_token
      target: k8s_token
    - source: k8s_prod_addr
      target: k8s_addr
    when:
      event: deployment
      environment: production
