kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 50

steps:
# Fetch git sub-modules
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive --remote

# Build
- name: build
  image: maven:3.9.7
  commands:
    - cd kafka-elastic-sink-connector && mvn clean package && cd ..
#    - cd debezium && mvn clean package -DskipTests=true && cd ..
  when:
    event:
      - push
      - tag
    branch:
      - master

# publish image in gce registry
- name: publish
  image: plugins/gcr
  settings:
    project: sansar-299400
    registry: gcr.io
    repo: sansar-299400/kafka-connect
    tags:
      - ${DRONE_BRANCH//\//_}
      - ${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    json_key:
      from_secret: GOOGLE_CREDENTIALS
  when:
    event:
      - push

# publish release image in gce registry
- name: publish-tag
  image: plugins/gcr
  settings:
    project: sansar-299400
    registry: gcr.io
    repo: sansar-299400/kafka-connect
    tags:
      - '${DRONE_TAG}'
      - latest
    json_key:
      from_secret: GOOGLE_CREDENTIALS
  when:
    event:
      - tag

# deploy-nightly
- name: deploy-nightly
  image: nytimes/drone-gke
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  settings:
    cluster: sansar-prod
    expand_env_vars: true
    template: k8s/k8s.yaml
    namespace: default
    skip_secret_template: true
    zone: asia-south2-b
    vars:
      app: kafka-connect
      stack: storiqa
      image: gcr.io/sansar-299400/kafka-connect:${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
  when:
    branch:
      - master
    event:
      - push

# deploy stage
- name: deploy-stage
  image: nytimes/drone-gke
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  settings:
    cluster: sansar-prod
    expand_env_vars: true
    template: k8s/k8s.yaml
    namespace: default
    skip_secret_template: true
    zone: asia-south2-b
    vars:
      app: kafka-connect
      stack: storiqa
      image: gcr.io/sansar-299400/kafka-connect:'${DRONE_TAG}'
  when:
    event:
      - tag

# deploy stable
- name: deploy-stable
  image: nytimes/drone-gke
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  settings:
    cluster: sansar-prod
    expand_env_vars: true
    template: k8s/k8s.yaml
    namespace: default
    skip_secret_template: true
    zone: asia-south2-b
    vars:
      app: kafka-connect
      stack: storiqa
      image: gcr.io/sansar-299400/kafka-connect:${DRONE_BRANCH//\//_}${DRONE_PARENT_BUILD_NUMBER}
  when:
    target:
      - stable

# deploy production
- name: deploy-production
  image: nytimes/drone-gke
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  settings:
    cluster: sansar-prod
    expand_env_vars: true
    template: k8s/k8s.yaml
    namespace: default
    skip_secret_template: true
    zone: asia-south2-b
    vars:
      app: kafka-connect
      stack: storiqa
      image: gcr.io/sansar-299400/kafka-connect:'${DRONE_TAG}'
  when:
    target:
      - production
