apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.app}}
  labels:
    app: {{.app}}
    stack: {{.stack}}
spec:
  selector:
    matchLabels:
      app: {{.app}}
      stack: {{.stack}}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{.app}}
      labels:
        app: {{.app}}
        stack: {{.stack}}
    spec:
      imagePullSecrets:
      - name: stq
      containers:
      - name: {{.app}}
        image: {{.image}}
        ports:
        - containerPort: 8083
        env:
          - name: BOOTSTRAP_SERVERS
            value: http://broker:9092
          - name: GROUP_ID
            value: connector-elastic
          - name: CONFIG_STORAGE_TOPIC
            value: connect-configs-logger
          - name: OFFSET_STORAGE_TOPIC
            value: connect-offsets-logger
          - name: STATUS_STORAGE_TOPIC
            value: connect-status-logger
          - name: KEY_CONVERTER
            value: io.confluent.connect.avro.AvroConverter
          - name: VALUE_CONVERTER
            value: io.confluent.connect.avro.AvroConverter

          - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
            value: http://schema-registry:8081
          - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
            value: http://schema-registry:8081

          - name: INTERNAL_KEY_CONVERTER
            value: org.apache.kafka.connect.json.JsonConverter
          - name: INTERNAL_VALUE_CONVERTER
            value: org.apache.kafka.connect.json.JsonConverter
          - name: REST_ADVERTISED_HOST_NAME
            value: "kafka-connect"
          - name: LOG4J_ROOT_LOGLEVEL
            value: INFO
          - name: LOG4J_LOGGERS
            value: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR,io.debezium=INFO,org.skynyrd=DEBUG"
          - name: KAFKA_HEAP_OPTS
            value: "-Xms500M -Xmx800M"
          - name: CONFIG_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: OFFSET_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: STATUS_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: PLUGIN_PATH
            value: /etc/kafka-connect/plugins
          - name: ES_URL
            value: http://stores-es:9200
        resources: {}
      hostname: kafka-connect
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{.app}}
  labels:
    app: {{.app}}
    stack: {{.stack}}
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    app: {{.app}}
    stack: {{.stack}}
